import "./App.css";
import Pagination from "./pages/Pagination";

function App() {
  const students = [
    "Abbas Akbar",
    "Abhinav sharma",
    "Abhishek Bansal",
    "Abhishek Srivastava",
    "Aditya Kumar Singh",
    "Ali Sher Khan",
    "Ananya Lamba",
    "Anjali Debnath",
    "Ankit Saini",
    "Anoushka gautam",
    "Ansh Kumar Gupta",
    "Anshika Bhatnagar",
    "Anuj Chauhan",
    "Anurag Saini",
    "Arin Saxena",
    "Ashish Ansh",
    "Avni saxena",
    "Divyanshi Vishnoi",
    "Inayat Ullah Khan",
    "Kratika Agarwal",
    "Manish Kumar",
    "Manit rastogi",
    "Nikita Rathore",
    "Prakhar Sharma",
    "Prakriti Gupta",
    "Pranjal Agarwal",
    "Prince Saxena",
    "Sakshi Chauhan",
    "Samarth Rastogi",
    "Samra Rubab",
    "Sandeep Kumar",
    "Sarthak rastogi",
    "Shashank johri",
    "Shashwat Tewari",
    "Shivam Prajapati",
    "Shivi Agarwal",
    "Shrey Singhal",
    "Sohil Ansari",
    "Tahir Ali",
    "Tahzeeb Malik",
    "Tanu Saini",
    "Vishal kumar",
    "Abbas Akbar",
    "Abhinav sharma",
    "Abhishek Bansal",
    "Abhishek Srivastava",
    "Aditya Kumar Singh",
    "Ali Sher Khan",
    "Ananya Lamba",
    "Anjali Debnath",
    "Ankit Saini",
    "Anoushka gautam",
    "Ansh Kumar Gupta",
    "Anshika Bhatnagar",
    "Anuj Chauhan",
    "Anurag Saini",
    "Arin Saxena",
    "Ashish Ansh",
    "Avni saxena",
    "Divyanshi Vishnoi",
    "Inayat Ullah Khan",
    "Kratika Agarwal",
    "Manish Kumar",
    "Manit rastogi",
    "Nikita Rathore",
    "Prakhar Sharma",
    "Prakriti Gupta",
    "Pranjal Agarwal",
    "Prince Saxena",
    "Sakshi Chauhan",
    "Samarth Rastogi",
    "Samra Rubab",
    "Sandeep Kumar",
    "Sarthak rastogi",
    "Shashank johri",
    "Shashwat Tewari",
    "Shivam Prajapati",
    "Shivi Agarwal",
    "Shrey Singhal",
    "Sohil Ansari",
    "Tahir Ali",
    "Tahzeeb Malik",
    "Tanu Saini",
    "Vishal kumar",
    "Abbas Akbar",
    "Abhinav sharma",
    "Abhishek Bansal",
    "Abhishek Srivastava",
    "Aditya Kumar Singh",
    "Ali Sher Khan",
    "Ananya Lamba",
    "Anjali Debnath",
    "Ankit Saini",
    "Anoushka gautam",
    "Ansh Kumar Gupta",
    "Anshika Bhatnagar",
    "Anuj Chauhan",
    "Anurag Saini",
    "Arin Saxena",
    "Ashish Ansh",
    "Avni saxena",
    "Divyanshi Vishnoi",
    "Inayat Ullah Khan",
    "Kratika Agarwal",
    "Manish Kumar",
    "Manit rastogi",
    "Nikita Rathore",
    "Prakhar Sharma",
    "Prakriti Gupta",
    "Pranjal Agarwal",
    "Prince Saxena",
    "Sakshi Chauhan",
    "Samarth Rastogi",
    "Samra Rubab",
    "Sandeep Kumar",
    "Sarthak rastogi",
    "Shashank johri",
    "Shashwat Tewari",
    "Shivam Prajapati",
    "Shivi Agarwal",
    "Shrey Singhal",
    "Sohil Ansari",
    "Tahir Ali",
    "Tahzeeb Malik",
    "Tanu Saini",
    "Vishal kumar",
    "Abbas Akbar",
    "Abhinav sharma",
    "Abhishek Bansal",
    "Abhishek Srivastava",
    "Aditya Kumar Singh",
    "Ali Sher Khan",
    "Ananya Lamba",
    "Anjali Debnath",
    "Ankit Saini",
    "Anoushka gautam",
    "Ansh Kumar Gupta",
    "Anshika Bhatnagar",
    "Anuj Chauhan",
    "Anurag Saini",
    "Arin Saxena",
    "Ashish Ansh",
    "Avni saxena",
    "Divyanshi Vishnoi",
    "Inayat Ullah Khan",
    "Kratika Agarwal",
    "Manish Kumar",
    "Manit rastogi",
    "Nikita Rathore",
    "Prakhar Sharma",
    "Prakriti Gupta",
    "Pranjal Agarwal",
    "Prince Saxena",
    "Sakshi Chauhan",
    "Samarth Rastogi",
    "Samra Rubab",
    "Sandeep Kumar",
    "Sarthak rastogi",
    "Shashank johri",
    "Shashwat Tewari",
    "Shivam Prajapati",
    "Shivi Agarwal",
    "Shrey Singhal",
    "Sohil Ansari",
    "Tahir Ali",
    "Tahzeeb Malik",
    "Tanu Saini",
    "Vishal kumar",
  ];
  return (
    <div className="App">
      <Pagination students={students} />
    </div>
  );
}

export default App;
